server:
  port: 8189
  servlet:
    context-path: /market-core
spring:
  flyway:
    check-location: true
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/market
    username: postgres
    password: Bb123456789
  jpa:
    show-sql: true
    properties:
      hibertnate:
        dialect: org.hibernate.dialect.PostgreSql
integrations:
  cart-service:
    url: http://localhost:8190/market-carts/
    connectTimeout: 5000
    readTimeout: 10000
    writeTimeout: 5000